@base = http://localhost:9090
#@base = https://staging.1.source.collected.design
###

{{base}}

###
{{base}}/404

###
DOWNLOADS
###

###
{{base}}/github/seek-oss/seek-style-guide/master/command:list

###
{{base}}/github/RoyalIcing/lofi-bootstrap/master/command:list

###
{{base}}/github/RoyalIcing/lofi-bootstrap/master2/command:list

###
{{base}}/github/RoyalIcing/lofi-bootstrap/master/command:list?content

###
{{base}}/github/RoyalIcing/lofi-bootstrap/master/command:list?content
Accept: application/x-ndjson

###
POST {{base}}/minecoin
